apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-configure-kibana
spec:
  template:
    spec:
      volumes:
      - name: import-json-secret 
        secret:
          secretName: import-json-secret
      containers:
      - name: "create-dashboard"
        volumeMounts:
        - name: import-json-secret
          mountPath: /etc/imports
        image: yauritux/busybox-curl
        env:
        - name: URL
          value: http://{{ .Release.Name }}-kibana:5601
        command:
        - "sh"
        - "-c"
        - |
          echo "WOOHOO!"
          ls imports
          cp /etc/imports/IMPORT_JSON /etc/import.ndjson
          echo "$(cat /etc/imports/IMPORT_JSON)"
          while [[ "$(curl -s -o /dev/null -w '%{http_code}\n' -L http://{{ .Release.Name }}-kibana:5601)" != "200" ]]; do sleep 1; done
          echo "READY!"
          curl -XPOST "http://{{ .Release.Name }}-kibana:5601/api/saved_objects/_import" -H 'kbn-xsrf: true' --form file=@/etc/import.ndjson
      restartPolicy: Never
  backoffLimit: 4
    