apiVersion: v1
kind: ConfigMap
metadata:
  name: config-metricbeat-configmap
data:
  metricbeat.yml: |
    metricbeat.config.modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: false
    setup.template.settings:
      index.number_of_shards: 1
      index.codec: best_compression
    logging.level: debug
    logging.to_files: true
    setup.kibana:
      host: {{ .Release.Name }}-kibana:5601
    output.elasticsearch:
      hosts: ["elasticsearch-master:9200"]
      #username: "elastic"
      #password: "test123"
    processors:
    - add_host_metadata: ~
    - add_cloud_metadata: ~