# Eventually this may be one per pod?
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-metricbeat-deployment
  labels:
    app: metricbeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metricbeat
  template:
    metadata:
      labels:
        app: metricbeat
    spec:
      serviceAccountName: linview-oss-service-account
      imagePullSecrets:
      - name: registry-linview-private  #(if using enterprise Linview)
      volumes:
      - name: py-config
        configMap:
          name: config-metricbeat-configmap
      containers:
      - name: metricbeat    
        imagePullPolicy: Always
        image: registry.digitalocean.com/linview-private/linview-oss-metricbeat   
        volumeMounts:
        - name: py-config
          mountPath: /etc/metricbeat/config/metricbeat.yml
          subPath: metricbeat.yml
        env:
        - name: HOST_IP
          value: "piraeus-controller.piraeus-system.svc.cluster.local"
        - name: HOST_PORT
          value: "3370"
        - name: ELASTIC_IP
          value: "elasticsearch-master"
        - name: ELASTIC_PORT
          value: "9200"
        - name: KIBANA_IP
          value: "{{ .Release.Name }}-kibana"
        - name: KIBANA_PORT
          value: "5601"
        command: 
         - bash
         - -c
         - "./etc/entrypoint.sh"
