metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
setup.kibana:
  host: 172.16.1.3:5601
output.elasticsearch:
  hosts: ["172.16.1.2:9200"]
  username: "elastic"
  password: "KIBANAPASS"
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~