ARG OPENDISTRO_VERSION

# https://github.com/elastic/elasticsearch-docker
FROM amazon/opendistro-for-elasticsearch:${OPENDISTRO_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
