# Linview OSS Helm Chart

metricbeat: {}
kibana:
  # Import dashboard from configmap 
  secretMounts:
  - name: import-json-secret
    secretName: import-json-secret
    path: /etc/import.json
    subPath: import.json 
  lifecycle:
    postStart:
      exec:
        command:
          - bash
          - -c
          - |
            #!/bin/bash
            KB_URL=http://localhost:5601
            while [[ "$(curl -s -o /dev/null -w '%{http_code}\n' -L $KB_URL)" != "200" ]]; do sleep 1; done
            curl -XPOST "$KB_URL/api/kibana/dashboards/import" -H "Content-Type: application/json" -H 'kbn-xsrf: true' -d @/etc/import.json

elasticsearch:
  esConfig: 
    elasticsearch.yml: |
      cluster.name: "docker-cluster"
      network.host: 0.0.0.0
      discovery.type: single-node
      xpack.license.self_generated.type: trial
      xpack.security.enabled: true
      xpack.monitoring.collection.enabled: true

ingress:
  enabled: false
  annotations:
    {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
