# Linview OSS Helm Chart

metricbeat: {}
kibana:
  resources:
    requests:
      cpu: "1400m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"
  ingress:
    enabled: true
    annotations: {}
    path: /
    hosts:
      - test.example.com
  kibanaConfig:
    kibana.yml: |
      elasticsearch.hosts: [ "http://elasticsearch-master:9200" ]
      elasticsearch.username: elastic
      elasticsearch.password: test123
      monitoring.enabled: false
  secretMounts:
  - name: import-json-secret
    secretName: import-json-secret
    path: /etc/import.json
    subPath: import.json 
  extraContainers:
    - name: "create-dashboard"
      volumeMounts:
        - name: import-json-secret
          mountPath: /etc/imports
      image: yauritux/busybox-curl
      command:
        - "sh"
        - "-c"
        - |
          echo "WOOHOO!"
          ls imports
          cp /etc/imports/IMPORT_JSON /etc/import.ndjson
          echo "$(cat /etc/imports/IMPORT_JSON)"
          sleep 120s
          echo "READY!"
          curl -XPOST "http://0.0.0.0:5601/api/saved_objects/_import" -H 'kbn-xsrf: true' --form file=@/etc/import.ndjson
        

elasticsearch:
  esJavaOpts: "-Xmx2g -Xms2g"
  antiAffinity: "soft"
  enableServiceLinks: false
  resources:
    requests:
      cpu: "1400m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "6Gi"
  #esConfig: 
  #  elasticsearch.yml: |
  #    xpack.license.self_generated.type: trial
  #    xpack.security.enabled: true
  #    xpack.monitoring.collection.enabled: true

ingress:
  enabled: false
  annotations:
    {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
