# Linview OSS Helm Chart

metricbeat:
  extraVolumes:
    - name: generate-py
      configMap:
        name: metricbeat-generation-configmap
    - name: py-reqs
      configMap:
        name: metricbeat-python-cm
    - name: configdisk
      emptyDir: {}
  extraEnvs:
    - name: HOST_IP
      value: "10.245.95.98"
    - name: HOST_PORT
      value: "3700"
  extraVolumeMounts:
    - name: generate-py
      mountPath: /etc/metricbeat/python-scripts/generateMetricbeat.py
      subPath: generateMetricbeat.py
    - name: generate-py
      mountPath: /etc/metricbeat/python-scripts/requirements.txt
      subPath: requirements.txt
  metricbeatConfig:
    metricbeat.yml: |
      metricbeat.config.modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
      setup.template.settings:
        index.number_of_shards: 1
        index.codec: best_compression
      output.elasticsearch:
        hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
        username: "elastic"
        password: "test123"
      processors:
        - add_host_metadata: ~
        - add_cloud_metadata: ~
kibana:
  # Import dashboard from configmap 
  secretMounts:
  - name: import-json-secret
    secretName: import-json-secret
    path: /etc/import.json
    subPath: import.json 
  lifecycle:
    postStart:
      exec:
        command:
          - bash
          - -c
          - |
            #!/bin/bash
            KB_URL=http://localhost:5601
            while [[ "$(curl -s -o /dev/null -w '%{http_code}\n' -L $KB_URL)" != "200" ]]; do sleep 1; done
            curl -XPOST "$KB_URL/api/kibana/dashboards/import" -H "Content-Type: application/json" -H 'kbn-xsrf: true' -d @/etc/import.json

elasticsearch:
  esConfig: 
    elasticsearch.yml: |
      cluster.name: "docker-cluster"
      network.host: 0.0.0.0
      discovery.type: single-node
      xpack.license.self_generated.type: trial
      xpack.security.enabled: true
      xpack.monitoring.collection.enabled: true

ingress:
  enabled: false
  annotations:
    {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
