# Linview OSS Helm Chart

metricbeat: {}
kibana:
  # Import dashboard from configmap 
  kibanaConfig:
    kibana.yml: |
      server.name: kibana
      server.host: "0"
      elasticsearch.hosts: [ "http://elasticsearch:9200" ]
      xpack.monitoring.ui.container.elasticsearch.enabled: true
      elasticsearch.username: elastic
      elasticsearch.password: test123
      monitoring.enabled: false
      kibana.defaultAppId: "dashboard/72c15740-f62f-11e9-a2ca-e9849bcad155"
  secretMounts:
  - name: import-json-secret
    secretName: import-json-secret
    path: /etc/import.json
    subPath: import.json 
  lifecycle:
    postStart:
      exec:
        command:
          - bash
          - -c
          - |
            #!/bin/bash
            echo "DOING IT NOW"
            KB_URL=http://localhost:5601
            while [[ "$(curl -s -o /dev/null -w '%{http_code}\n' -L $KB_URL)" != "200" ]]; do sleep 1; done
            curl -XPOST "$KB_URL/api/kibana/dashboards/import" -H "Content-Type: application/json" -H 'kbn-xsrf: true' -d @/etc/import.json

elasticsearch:
  esConfig: 
    elasticsearch.yml: |
      xpack.license.self_generated.type: trial
      xpack.security.enabled: true
      xpack.monitoring.collection.enabled: true

ingress:
  enabled: false
  annotations:
    {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
